[package]
name = "etl-app"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = { workspace = true }
kanal = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-retry = { workspace = true }
